name: imyong_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tnd_core:
    git:
      url: "https://git.technolda.com/Technolda/tnd_core.git"
      ref: v2
  tnd_pkg_widget:
    git:
      url: "https://git.technolda.com/Technolda/tnd_pkg_widget.git"
      ref: v2
  tnd_pkg_repository:
    git:
      url: "https://git.technolda.com/Technolda/tnd_pkg_repository.git"
      ref: v2

  hive: 2.0.4
  hive_flutter: 1.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
